//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BachHoaXanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDanhGias = new HashSet<ChiTietDanhGia>();
            this.ChiTietDatHangs = new HashSet<ChiTietDatHang>();
            this.ChiTietThongKeThangs = new HashSet<ChiTietThongKeThang>();
            this.CTPhieuNhapKhoes = new HashSet<CTPhieuNhapKho>();
            this.NhaCungCaps = new HashSet<NhaCungCap>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string HinhSanPham { get; set; }
        public decimal GiaNiemYet { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<short> KhoiLuong { get; set; }
        public Nullable<short> DungTich { get; set; }
        public string ThanhPhan { get; set; }
        public string CachDung { get; set; }
        public string BaoQuan { get; set; }
        public string LuuY { get; set; }
        public string NoiSanXuat { get; set; }
        public string MoTa { get; set; }
        public short SoLuongTon { get; set; }
        public string TrangThai { get; set; }
        public short MaDanhMuc { get; set; }
        public Nullable<short> MaThuongHieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDanhGia> ChiTietDanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatHang> ChiTietDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThongKeThang> ChiTietThongKeThangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuNhapKho> CTPhieuNhapKhoes { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhaCungCap> NhaCungCaps { get; set; }
    }
}
