//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BachHoaXanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeTheoThang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongKeTheoThang()
        {
            this.ChiTietThongKeThangs = new HashSet<ChiTietThongKeThang>();
        }
    
        public short Thang { get; set; }
        public short TongSoLuongThang { get; set; }
        public decimal TongDoanhThuThang { get; set; }
        public short Nam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThongKeThang> ChiTietThongKeThangs { get; set; }
        public virtual ThongKeTheoNam ThongKeTheoNam { get; set; }
    }
}
